/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual.interfaces;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.UIManager;


import Clases.Cliente;

import Model.ConfTabla;
import Model.Modelo;
import Model.Query;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;

import Controler.ControlData;
import Controler.Controlador;
import Visual.Interfaz;

/**
/**
 *
 * @author framo
 */
public class ListaClientes extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public ListaClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AgregarBoton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PanelLista = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        jPanel1.setMinimumSize(new java.awt.Dimension(1270, 710));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgregarBoton.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        AgregarBoton.setText("Agregar");
        AgregarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBotonActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 90, 30));

        jScrollPane1.setHorizontalScrollBar(null);

        PanelLista.setLayout(new javax.swing.BoxLayout(PanelLista, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(PanelLista);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1260, 640));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/magnifier-1_icon-icons.com_56924.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 190, 30));

        jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jButton2.setText("Caducados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        LeerClientes();
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBotonActionPerformed
      AgregarCliente nuevocliente = new AgregarCliente();
      nuevocliente.setVisible(true);

    nuevocliente.guardar.addActionListener(new ActionListener() {
    public void actionPerformed(ActionEvent e) {
      
      String nom = nuevocliente.nombre.getText();
      String tel = nuevocliente.telefono.getText();
      String correo = nuevocliente.correo.getText();
      System.out.println(nom + tel + correo);
      PanelCliente pcliente = new PanelCliente(nom,tel,correo);
      PanelLista.add(pcliente);
      PanelLista.updateUI();  
      
    }
    });
      


    }//GEN-LAST:event_AgregarBotonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Caducados().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void LeerClientes() {//GEN-FIRST:event_AgregarBotonActionPerformed
        conect();
        List<Cliente> clientes = new ArrayList<Cliente>();
        clientes = ControlData.mostrarclientes();
        try
        {
            for(int x =0;x<clientes.size();x++)
            {
                System.out.print(clientes.get(x).getNombre());
                PanelCliente pcliente = new PanelCliente();
                pcliente.Nombre = clientes.get(x).getNombre() + " " + clientes.get(x).getApe();
                pcliente.Fecha_S = clientes.get(x).getCorreo();
                pcliente.NumBarco += " " + clientes.get(x).getbarcos();
                pcliente.initComponents();
                PanelLista.add(pcliente);
                PanelLista.updateUI();
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }

      }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        FlatLightLaf.setup();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaClientes().setVisible(true);
            }
        });
    }
        public static void conect()
        {
            try
            {
                ControlData.Conect();
                //System.out.println(Query.registrar(cc, "Palomon", "121234", "Ni idea", "Wakanda", "Vibranio"));
                
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarBoton;
    private javax.swing.JPanel PanelLista;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
